name: file_access
description: A Flutter package to handel files on Web, Desktop and Mobile instead of File.io
version: 1.0.3
homepage: https://github.com/rodydavis/file_access

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^1.5.0+2
  image_picker: ^0.6.3+4
  file_chooser:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/file_chooser
      ref: 040f36c82b63e8764ec2fd97066767503a667b6d

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
